Add Snapping Mode to custom modes
mapbox/mapbox-gl-draw pull request #1022
Opened 2020-11-24 20:23 UTC by mhsattarian

2021-01-05 11:20 UTC, clementmas requested changes

2021-01-05 11:20 UTC, clementmas commented on docs/MODES.md
> +-   [Pinning Mode](https://github.com/mhsattarian/mapbox-gl-draw-snap-mode): Pin shared coordinates together during edit
```suggestion
-   [Pinning Mode](https://github.com/mhsattarian/mapbox-gl-draw-pinning-mode): Pin shared coordinates together during edit
```

2021-01-05 11:20 UTC, clementmas commented on docs/MODES.md
> +-   [Passing Mode](https://github.com/mhsattarian/mapbox-gl-draw-snap-mode): Add ability to draw features but don't add them
```suggestion
-   [Passing Mode](https://github.com/mhsattarian/mapbox-gl-draw-passing-mode): Add ability to draw features but don't add them
```

2021-01-05 11:55 UTC, mhsattarian commented on docs/MODES.md
> +-   [Passing Mode](https://github.com/mhsattarian/mapbox-gl-draw-snap-mode): Add ability to draw features but don't add them
Ah, My bad. thanks for the edits.

2021-08-11 21:22 UTC, mhsattarian commented
Sorry for making this PR pop up again, I just realized I'd forgotten to resolve changes suggested by @clementmas.

2022-11-27 08:42 UTC, mhsattarian commented
I've added one more mode I created recently.
and can this be finally merged? this PR has been open for around 2 years!

2024-03-11 02:07 UTC, 3zzy commented
@mhsattarian Great work! Sad that its not been merged yet :(

2024-06-03 19:04 UTC, mhsattarian commented
Thanks @3zzy, I don't know why either. it's taking so long that I don't work on GIS-related applications anymore!

I really like and respect the Mapbox team's work and effort. I don't know why such a useful project has such slow progress.

2024-06-28 15:44 UTC, stepankuzmin approved these changes
Thanks for the contribution, @mhsattarian!

2024-06-28 15:45 UTC, merged