Remove Static mode from the constants and use Expressions syntax in theme.js
mapbox/mapbox-gl-draw pull request #1078
Opened 2021-10-28 16:58 UTC by oodavid

Please see the following videos:

* [Overview of the pull-request](https://www.loom.com/share/eb9bc754e6344b0598e4457d1e13c513) - 4min video
* [Changes to theme.js](https://www.loom.com/share/17865dfbd73f467dbb02f9f6c70b4117) - 4min video

2023-01-30 15:40 UTC, stepankuzmin requested changes
Hi @oodavid! Thanks for the contribution, this looks good to me, especially the nicer UX 👍  However, there are 3 failing tests if I run this locally. Could you please rebase on top of the `main` branch and fix them, so we can merge this into the upcoming release? Thanks! 🙏

2023-01-30 15:50 UTC, oodavid commented
Ooh, now there's a question!

I'll have to jog my memory, might have the chance to take a peek tonight.

2023-08-20 16:51 UTC, SnailBones approved these changes

2024-06-28 14:44 UTC, stepankuzmin approved these changes
Hey everyone! Thanks again for the contribution, @oodavid, and sorry it took so long to review. I'm merging this along with the core changes from the neighboring PR https://github.com/mapbox/mapbox-gl-draw/pull/1221. We plan to release a new version of Mapbox GL Draw, and these changes will be available in the upcoming release.

2024-06-28 14:44 UTC, merged